plone/mockup

CHANGES.rst
mockup/patterns/resourceregistry/js/fields.js
mockup/patterns/resourceregistry/js/registry.js

I was wondering, how someone can find out if and when a bundle was compiled.
Therefore: In the resource registry bundle detail view, add the fields last_compilation, jscompilation and csscompilation for display.  This gives more insight about the state of each bundle.
plus a small fix in the ``_buildCSSBundle`` iframe template.

Resource registry: show bundle compilation metadata

---

CHANGES.rst
mockup/patterns/relateditems/pattern.js
mockup/patterns/relateditems/pattern.relateditems.less
mockup/patterns/tinymce/pattern.js
mockup/tests/pattern-relateditems-test.js
mockup/tests/pattern-tinymce-test.js

add content icon to relateditems pattern

---

CHANGES.rst
mockup/js/utils.js
mockup/patterns/relateditems/pattern.js
mockup/patterns/structure/js/views/tablerow.js
mockup/patterns/structure/pattern.js
mockup/patterns/structure/templates/tablerow.xml
mockup/patterns/tinymce/pattern.js
mockup/patterns/tinymce/templates/result.xml
mockup/patterns/tinymce/templates/selection.xml
mockup/patterns/upload/pattern.js
mockup/tests/fakeserver.js
mockup/tests/json/contextInfo.json
mockup/tests/pattern-relateditems-test.js
mockup/tests/pattern-structure-test.js
mockup/tests/pattern-tinymce-test.js
mockup/tests/utils-test.js

Change all index references from Type to portal_type. E.g. the TinyMCE configuration option containsobjects expects portal_type values, not Type.
I had an issue with having 'Document' declared as folderish via an tinymce.xml 'containsobjects' entry, but the TinyMCE pattern wasn't respecting it (even with some necessary changes in plone.app.widgets.utils, for which i'll create a separate pull-request). It was due to mockup querying for the Type index, which is the title of the content type. In my case, the title is not Document, but Page.
IMO, we should remove the Type index at all and only use portal_type, but this is another discussion (or PLIP).
See https://github.com/plone/Products.TinyMCE/blob/master/Products/TinyMCE/profiles/default/tinymce.xml#L15 for tinymce declaring "Document" as …

Change index references from Type to portal_type

---

CHANGES.rst
bower.json
mockup/js/config.js
mockup/patterns/tinymce/js/links.js
mockup/patterns/upload/less/pattern.upload.less
mockup/patterns/upload/pattern.js

TinyMCE and upload pattern: Re-add triggering of the ``uploadAllCompleted`` event and pass the server's response and path uid to it. TinyMCE's link plugin is listening to it and uses the information to create a URL out of the uploaded files. Fixes #471.
Update Dropzone.js to it's latest 4.0.1 version.

TinyMCE link/image upload fix + dropzone update

---

mockup/patterns/tinymce/pattern.js

I made a little mistake in pull request #491

fix name mixup that caused image button/menu to be broken

---

mockup/patterns/filemanager/pattern.js
mockup/patterns/thememapper/pattern.js
mockup/patterns/thememapper/pattern.thememapper.less

Added a button to the thememapper that shows the Ace editor window in fullscreen, as requested in #476. Also fixed a minor issue causing Ace to resize incorrectly when its container size was changed.

Thememapper fullscreen

---

Makefile

This target runs mockup tests and saves the results in an XML file
so that jenkins can show them with its publishers.
Depends on https://github.com/plone/mockup-core/pull/29

Add test-jenkins

---

mockup/patterns/filemanager/js/delete.js
mockup/patterns/filemanager/pattern.filemanager.less
mockup/patterns/filemanager/pattern.js
mockup/patterns/thememapper/pattern.js
mockup/patterns/thememapper/pattern.thememapper.less
mockup/tests/pattern-thememapper-test.js

Reorganized the navigation in the filemanager to be much easier to work with, and to remove countless small issues involving the navigation tree/tabs. 
Added icons to the buttons in the thememapper, and to the navigation tree.
Added a feature support test for the filemanager's uploadview.
Fixed a few broken tests.
Lot of changes here, input?

Filemanager navigation overhaul.

---

mockup/patterns/filemanager/pattern.js
mockup/patterns/thememapper/js/lessbuilderview.js
mockup/patterns/thememapper/pattern.js

Fixes a bug that cases the thememapper's LESS builder from converting characters to entities (< to &lt;...etc)
Also gives the filemanager tree the ability to differentiate between files, images, and other non-theme files.

Fixes problems with the thememapper's LESS builder

---

CHANGES.rst
mockup/patterns/filemanager/js/addnew.js
mockup/patterns/filemanager/js/delete.js
mockup/patterns/filemanager/js/newfolder.js
mockup/patterns/filemanager/js/rename.js
mockup/patterns/filemanager/pattern.js
mockup/patterns/thememapper/js/lessbuilderview.js
mockup/patterns/thememapper/pattern.js
mockup/patterns/thememapper/pattern.thememapper.less

Fixes/adds several features to the thememapper:
- Let's users specify a filename when building LESS into CSS
- Adds button to reload a file from server
- "Build CSS" button is now disabled, instead of hidden when editing a non-less file, to maintain a      consistent button layout
- Pasting text into the Ace editor will now mark the file as "modified" properly
- The filemanager tree now stays open after a add new/delete/upload/rename
- Renaming a file to a previously-but-no-longer-existent filename will now correctly load the new version of the file
- Slightly changed the highlighting scheme in the thememapper tree to make folder selection more intuitive
- Changed styling of the toolbar buttons to be both more consistent with Plone, and to allow for more buttons on screen
There's a lot …

Thememapper updates

---

mockup/patterns/thememapper/js/lessbuilderview.js
mockup/patterns/thememapper/pattern.js

Fixes the lessbuilder throwing "less is undefined" when the user isn't in dev mode.
Added the option to remove absolute urls from CSS files built in the lessbuilder.
Goes along with: https://github.com/plone/plone.resourceeditor/pull/9

Relative urls

---

mockup/patterns/modal/pattern.js
mockup/tests/pattern-modal-test.js

Regular expression was failing when the data-attribute is not the last attribute in the tag, see:
- https://regex101.com/r/pI4kL9/1
I wanted to use jQuery instead of regexp bacause:
- we have it
- it is less error prone
- it is more clear
but it turns out it is too complicated to be cross browser.

Fix the regular expression

---

CHANGES.rst
mockup/patterns/tinymce/pattern.js
mockup/tests/pattern-tinymce-test.js

Add option to use tinyMCE inline on a contenteditable div. The pattern creates
the contenteditable div from the textarea, copies it's content to it and
handles saving changed data back to the textarea on form submit.

tinyMCE inline editing

---

CHANGES.rst
mockup/patterns/modal/pattern.modal.less

Raise pat-modal ``z-index`` to make sure, it's displayed above anything
else, e.g. TinyMCE's toolbar in inline editing mode.

Raise pat-modal z-index

---

CHANGES.rst
mockup/patterns/pickadate/pattern.js

This should add extra i18n labels for the pickadate widget needed for the
https://github.com/plone/Products.CMFPlone/issues/891
@vangheem  I have some question regarding the i18n process.
I ran:
<pre>make i18n</pre> 
This is advised in the readme of the mockup to generate a widgets.pot file.
Here is the diff for it and the widgets.pot from plone.app.locales
https://gist.github.com/ichim-david/83686321d847d4723e2e
EDIT: Basically the new labels for pickdate plugin are referenced from build/plone.js instead of patterns/pickadate/js/pattern.js plus some deleted strings which I don't know if they were still relevant.
I don't know if this is correct and if you need to pass any flags to the make  i18n command.
Running on buildout root:
<pre>bin/i18n-update-all</pre>
produced the following …

Refs CMFPlone #891 added more i18n strings to pickadate

---

CHANGES.rst
mockup/patterns/textareamimetypeselector/pattern.js
mockup/patterns/tinymce/pattern.js
mockup/tests/pattern-textareamimetypeselector-test.js
mockup/tests/pattern-tinymce-test.js

Fix inline tinyMCE to work together with mosaic. The inline option must now be passed to the patterns option object instead to the patterns tiny options object.

Inline tinyMCE / mosaic fix

---

mockup/patterns/moment/pattern.js

Currently if you select a language which isn't supported by moment.js the last language in the list of available languages is used (Chinese). This PR uses English as the fallback instead.
See plone/Products.CMFPlone#1028
I'm having trouble adding a test for this:
$('html').attr('lang', 'fr');
var $el = $('<div class="pat-moment" data-pat-moment="format:relative">' + date + '</div>');
registry.scan($el);
var i18n = new I18n();
console.log(i18n.currentLanguage);
Shows the language set to 'fr', but when I inspect pat-moment I see that new i18n()).currentLanguage is returning 'en-us'.

pat-moment: fall back to English

---

CHANGES.rst
mockup/patterns/structure/js/views/table.js
mockup/patterns/structure/pattern.js

I would like to be able to choose the moment formatting in structures. As I am fairly new to mockup, I don't know if this is the best way to do it (I tried with html attributes but it seems to not working because of the Moment pattern being initialized in JS ?).
Please also note that this is not based on master because of #589.

feat: add option to select moment format in structure

---

mockup/patterns/modal/pattern.js
mockup/tests/pattern-modal-test.js

The event handler on the inner wrapper which listens to clicks and decides whether a modal should be closed or not, was being hijacked by the first modal that was registered so that modal's config would have first say.
I updated the code to lazily create the backdrop, wrapper and inner wrapper, and I remove the wrapper afterwards, so that the click event is registered lazily per modal.
Fixes a problem @instification had at Plone conf sprint.

Modal fix: configs of additional modals in a page are ignored.

---

mockup/patterns/resourceregistry/js/registry.js

When we have a longer label (in the place "Development Mode(only logged in users)"), it goes in front of the buttons and we can't click on them anymore.

fix: separate buttons from checkbox label in the resource registry

---

CHANGES.rst
mockup/patterns/modal/pattern.js

My issue is with the static portlet. The add form is in a modal. Tinymce can open other modals (eg images/link). If I close this modal, it will close both of them.
This PR fixes that.

fix: modal when leaving a modal in a modal.

---

CHANGES.rst
mockup/patterns/relateditems/pattern.relateditems.less

The position of the widget related items (z-index) is high in relation to the added content menu.

Z-index error in widget related items

---

mockup/patterns/structure/templates/tablerow.xml

In folder_contents view, the news item icon doesn't appear because its portal_type is "News Item". The code in line 4 results in a class string "contenttype-news item", which effectively means two classes, "contenttype-news" and "item".
Another typical case where this fails is for custom content types, which by default with dexterity will be named something like "my.package.mytype". This results in the class string "contenttype-my.package.mytype" which can't be referenced in css, as it is illegal.
This patch simply replaces these cases with a dash. For news items, this results in contenttype-news-item, which is exactly how the news item icon is coded in contents.plone.less, so news items will immediately have an icon again.

Take complex portal types into account

---

CHANGES.rst
mockup/patterns/tinymce/less/pattern.tinymce.less

- Import TinyMCE ``Content.Objects.less`` from the lightgray skin in ``less``
mode, not ``Content.less`` in ``inline`` mode.
Fixes plone/Products.CMFPlone#755 - visual aids not visible.
``Content.Objects.less`` also doesn't overwrite our fonts.
- Enforce a ``min-width`` for tables while editing and visual aids turned on.
Fixes plone/Products.CMFPlone#920.
Actually it's more like another fix for plone/Products.CMFPlone#755
@vangheem - I think this could make https://github.com/plone/plonetheme.barceloneta/pull/31/files obsolete. See my comments there.

Fixes TinyMCE visual aid for tables and others

---

CHANGES.rst
mockup/patterns/querystring/pattern.js

where if existing querystring path value is ".::1", after edit, the wrong value will be selected
@obct537 can you review this. It's a hack of a fix so maybe you have a better idea on how to fix it.

Fix issue with query string widget

---

CHANGES.rst
mockup/patterns/querystring/pattern.js

The select is on simple mode by default event if the value is an advanced one.
Also fix a bug where the depth was -1.

fix: path widgets initialization in querystring pattern

---

mockup/patterns/structure/templates/paging.xml
mockup/patterns/structure/templates/selection_button.xml
mockup/patterns/structure/templates/selection_item.xml
mockup/patterns/structure/templates/table.xml
mockup/tests/pattern-structure-test.js

The Title attribute for a given object could be used as an XSS attack vector. If the attacker can create new object or modify the title an existing object within a Plone instance, then convince her victim (or anyone with access) to use the folder_contents view and select the affected item, this would then populate the raw title text into the selection well without being sanitized, triggering the XSS attack.
The UID field is also vulnerable, but irrelevant as an attack vector for a typical Plone instance.
This pull request contains the test that demonstrates this problem, and then the fix to address this.
The status text set during copy/cut/paste is also vulnerable, however the i18n translation seems to sidestep this issue within the Plone instance context. That said, this pull request …

Structure selection well XSS fix

---

mockup/tests/pattern-relateditems-test.js

Uncommented tests for the relateditems pattern and corrected the issues in the test harness to make it work again.

Uncomment realteditems tests

---

CHANGES.rst
mockup/patterns/relateditems/pattern.js
mockup/tests/pattern-relateditems-test.js

The embedded template uses `<%= value %>` for everything which enables XSS attack.  Replaced all of this with `<%- value %>` and made a note for `<%= item %>` as that contains markup generated by the breadCrumbs template.  Requires pull request #628 as I need all existing test to run because overzealous cleansing broke breadCrumbs, heh.
As an aside, should better review be in place in the first place to actually not let tests be removed without proper explanation? Also maybe need some automated audit of the usage of the `<%= value %>` syntax as part of the tests, because I don't like XSS in my CMS.  Though this second part is a difficult requirement to address at the moment as I see it.

Relateditems pattern XSS fix

---

CHANGES.rst
mockup/patterns/tinymce/js/links.js

Space at the beginning of an absolute link (" http://...") is encoded as %20, and thus the link is considered as relative. This trim the link to ensure this doesn't happen.

fix: trim links in tinymce before inserting them

---

CHANGES.rst
mockup/patterns/relateditems/pattern.js
mockup/tests/pattern-relateditems-test.js

There is no changelog yet because it does not seem to be completely fixed and I'm not sure this is the better way to do it, so I'd like to discuss it first.
The issue I have is that for certain related widget (in my case, in the collection portlet), the `vocabularyUrl` option is set to `@@getSource`, which cause the results to be filtered by the field parameters (in my case, only `Collections`).
So it is impossible to browser the site using the related items widget in the Collection portlet form. I was able to kinda solve it with this fix but I'd like some input.
* Is `$('body').attr('data-portal-url')` the best way to get the portal url in a mockup ?
* I seem to only be able to browser a single level when using the right arrow (probably because it uses the results from the actual …

fix: ensure we have all content for tree query in relateditems

---

CHANGES.rst
mockup/patterns/relateditems/pattern.js

Fix for https://github.com/plone/mockup/pull/596
Adding `self.options.treeOptions` there overrides the `vocabularyUrl` set earlier and it doesn't fallback on `self.options.vocabularyUrl`.

fix: treeQuery vocabularyUrl option in relateditems

---

CHANGES.rst
mockup/patterns/thememapper/pattern.js

Related to https://github.com/plone/Products.CMFPlone/issues/1468
The backend part is here https://github.com/plone/plone.resourceeditor/pull/17

Fix Build CSS button in thememapper with file system-based

---

CHANGES.rst
mockup/tests/fakeserver.js

~~- Update the moment library to ``2.12.0``.~~
- Fix fakeserver ``relateditems-test.json`` response to return ISO dates for ``CreationDate``, ``ModificationDate`` and ``EffectiveDate``, as they really do in Plone.
This resolves a moment deprecation warning in structure examples.

Moment Updates

---

CHANGES.rst
mockup/patterns/moment/pattern.js
mockup/tests/pattern-moment-test.js

Moment pattern: Don't try to parse obvious invalid dates ("None", "").
Avoids Moment.js deprecation warnings.

Moment: Don't parse invalid dates

---

CHANGES.rst
Makefile
mockup/js/grunt.js
mockup/less/base.less
mockup/patterns/structure/js/actionmenu.js
mockup/patterns/structure/js/models/result.js
mockup/patterns/structure/js/navigation.js
mockup/patterns/structure/js/views/actionmenu.js
mockup/patterns/structure/js/views/table.js
mockup/patterns/structure/js/views/tablerow.js
mockup/patterns/structure/less/pattern.structure.less
mockup/patterns/structure/pattern.js
mockup/patterns/structure/templates/actionmenu.xml
mockup/patterns/structure/templates/table.xml
mockup/patterns/structure/templates/tablerow.xml
mockup/tests/fakeserver.js
mockup/tests/pattern-structure-test.js
package.json

Here is a pull request with changes to structure pattern for some more config options (action menu, icon size), code cleanup, better view url support:
- Allow definition of action menu items not only as dropdowns but also as buttons.
- Add ``openItem`` and ``editItem`` actions as buttons and remove the open icon from the title column.
- Open ``openItem`` links according to ``typeToViewAction`` instead of default with the ``/view`` postfix.
- Open ``editItem`` under ``/@@edit`` instead ``/edit``.
- Remove JS event handlers for externally opening simple URLs and use the href attribute instead.
- Add ``iconCSS`` option for action menus items to add icons.
- Add ``modal`` option for action menus items to allow links open in a modal.
- Add ``iconSize`` option to set the icon size if a item has …

Structure pattern action items changes

---

CHANGES.rst
mockup/patterns/tinymce/js/links.js

mockup-patterns-autotoc was missing.

Re-add missing pattern dependencies in TinyMCE.

---

CHANGES.rst
mockup/patterns/structure/js/views/app.js
mockup/patterns/structure/templates/table.xml

Don't show empty alerts with ``alert-warning`` CSS class.
Show them transparent but in the same height as if they were not empty.
Align HTML structue with bootstrap ones and use ``<strong>`` for alert labels.nd an empty message aborts the commit.

Structure pattern: Alert design

---

CHANGES.rst
bower.json
mockup/js/config.js
mockup/tests/pattern-pickadate-test.js
mockup/tests/pattern-select2-test.js
package.json

Update safe bower.json dependencies except backbone which tests would fail.
Reason was to update tinymce....

update bower dependencies

---

mockup/patterns/tinymce/js/links.js

@vangheem After https://github.com/plone/mockup/commit/efd02e50904f55299eb7f00eddc6c9fcf762ffb1 have you still been able to add multiple new links with TinyMCE without reloading the edit page?
For me, because "init" is called only when the link modal is shown for the first time, all link actions affect the element which was selected for the first link action (e.g. adding in-line images will all go into the same place regardless of the cursor position after the first addition). Moving your added code from init to initData seem to have fixed that for me (because initData is called every time when modal is shown), but I'm not yet sure if it has any side effects.

Fix issue where TinyMCE selection position was not updated on modal re-shown

---

CHANGES.rst
mockup/patterns/querystring/pattern.js

Not sure why, but in my webpack-built bundles checks like foo !== undefined in querystring may fail (pass for undefined), but typeof foo !== 'undefined' works correctly.

Fix to check undefined with typeof foo === 'undefined'

---

CHANGES.rst
mockup/patterns/upload/less/pattern.upload.less

Upload pattern previously omitted any styles for progress bar, which breaks upload display of progress bar in plone.app.widgets 1.x (e.g. in TinyMCE upload tab).  
This fixes that; it also fixes lack of the bootstrap scaffolding for the .sr-only selector.
LESS Imports are done by reference to keep resulting file size low.  This style fix is very low risk: while it adds about 1.2k to the built widgets.min.css, once gzipped, the difference is only 64 additional bytes served over a compressed connection.

Include Upload pattern progress bar styles for use by widgets

---

CHANGES.rst
mockup/patterns/relateditems/pattern.js
mockup/patterns/relateditems/pattern.relateditems.less

See changelog. 
Justification(s):
(1) Most reasonable way to get icon compatibility on Plone 4 without breaking forward-compatibility with content icons in Plone 5 is to leverage the fact that Plone 5 getIcon returns a boolean in the JSON.  We can use this, and only serve image scale for Image portal_type as fallback (for Plone 4, this won't be issue for Plone 5).
(2) Scrollbar covers result buttons on Mac firefox.  Margin improves this.  Also, having on-hover color change for button helps delineate the expected action for the user vs. selecting the item.
@thet -- I'm pretty sure these minor changes do not conflict with your PR?

Minor related items fixes: Plone 4 icon compat; result button style

---

CHANGES.rst
mockup/js/grunt.js
package.json

So seems that grunt-sed is used in quite some places, so it can not be removed as my original idea was.
Fortunately there is a pull request to fix the dependency problems https://github.com/jharding/grunt-sed/pull/17 *and* npm allows to define versions as github URLs  (even so short that you don't need to say that they come from github).
Long story short: I forked the pull request's fork on collective (just to prevent that the fork removes the commits) so now jenkins and travis both run fine :-)

Use fork of grunt-sed

---

CHANGES.rst
mockup/less/ui.less
mockup/patterns/filemanager/pattern.filemanager.less
mockup/patterns/relateditems/pattern.relateditems.less
mockup/patterns/structure/less/pattern.structure.less
mockup/patterns/tooltip/pattern.js
mockup/patterns/tooltip/pattern.tooltip.less

Make ``pat-tooltip`` useable by it's own by including the necessary less files and reuse that one in other patterns.
Allow configuration of ``placement`` parameter.
Without this fix, pat-tooltip cannot be easily used - except the bootstrap tooltip less files are also included.
What I do not fully understand is the ``tooltips`` classes from the tooltip less file, which I removed. That markup seems not to be used, although it's also used in plonetheme.barceloneta: https://github.com/plone/plonetheme.barceloneta/blob/master/plonetheme/barceloneta/theme/less/tooltip.plone.less
However, what I would really prefer is to remove the pat-tooltip from here alltogether and use instead the one from patternslib: http://patternslib.com/tooltip/
That should be an easy replacement, because It seems that …

tooltip cleanup and fixes

---

CHANGES.rst
mockup/patterns/relateditems/pattern.js
mockup/patterns/relateditems/pattern.relateditems.less
mockup/patterns/relateditems/templates/toolbar.xml
mockup/patterns/tinymce/pattern.js
mockup/tests/pattern-relateditems-test.js

- Calculate all paths relative to the ``rootPath``, so that breadcrumbs navigation and favorites do not show paths outside the rootPath.
- Dont open related items favorites dropdown when hitting enter anywhere in the form.

relatedItems enhancements

---

CHANGES.rst
mockup/patterns/relateditems/pattern.js
mockup/patterns/relateditems/templates/result.xml
mockup/patterns/relateditems/templates/selection.xml
mockup/patterns/relateditems/upload.js

- For results and selected items with images, add a line break after the image.
- Add option to pass rootUrl for relateditems pattern to make upload view work in virtual hosting environments. Necessary since c7c14b6 . Goes together with: plone/plone.app.widgets#148
for the second one, there is no extra changelog entry as it is a bugfix for a feature which is not released yet.

fix related items upload + related items template opt

---

CHANGES.rst
mockup/patterns/tinymce/pattern.js

Currently configuring importcss-plugin is very limited, because even the plugin supports regexp filters here and there, those cannot be passed through pattern configuration. Therefore, I suspect, that almost nobody else has used importcss_groups and importcss_selector_filter -options.
This change would add implicit RegExp support for importcsss_selector_filter and filter part of each importcss_groups-value. I believe, this is backwards compatible, because replacing "myprefix" with RegExp("myprefix") should not have much effect.
http://archive.tinymce.com/wiki.php/Configuration:importcss_selector_filter
http://archive.tinymce.com/wiki.php/Configuration:importcss_groups

Add better support for TinyMCE importcss-plugin configuration through pattern

---

CHANGES.rst
mockup/patterns/upload/pattern.js

A click on the browse button of the related item widget currently opens the file browser for the file input.

fix: conflict between upload and relateditem browse button

---

CHANGES.rst
mockup/patterns/livesearch/pattern.js

For the searchbox, it is not possible to set `data-default-sort`.

feat: add defaultSortOn option in livesearch pattern

---

CHANGES.rst
mockup/js/utils.js
mockup/patterns/pickadate/pattern.js
mockup/patterns/pickadate/pattern.pickadate.less
mockup/tests/pattern-pickadate-test.js
mockup/tests/utils-test.js

- Remove the now obsolete footer buttons as a whole from the date picker.
- Add options ``today`` and  ``clear`` to hide those buttons when set to ``false``.
- Use display: inline-block instead of problematic float:left.
- Also, via a change in plone.app.widget, the "Clear" button is not shown for ``required`` date/time fields.
Also adresses: #732 
Related:
https://github.com/plone/Products.CMFPlone/pull/1947
https://github.com/plone/plone.app.widgets/pull/154
https://github.com/plone/mockup/pull/740
https://github.com/plone/plone.app.z3cform/pull/60
https://github.com/plone/Products.Archetypes/pull/78
https://github.com/plone/plonetheme.barceloneta/pull/123
Jenkins:
http://jenkins.plone.org/job/pull-request-5.1/1294/

More pickadate optimizations

---

CHANGES.rst
mockup/js/utils.js
mockup/patterns/relateditems/pattern.js

Related to #734 and #736.
It allows to change the query to be done on the portal root for example.

feat: add an option for the path operator in QueryHelper and tinymce pattern

---

CHANGES.rst
mockup/less/docs.less
mockup/less/filemanager.less
mockup/less/resourceregistry.less
mockup/less/structure.less
mockup/less/ui.less
mockup/less/widgets.less

Use the less variables for paths instead.
Fixes a case, where less files couldn't be found in Plone development mode.

Do not use relative paths for imports in less files.

---

CHANGES.rst
bower.json
mockup/js/ui/views/button.js
mockup/js/ui/views/buttongroup.js
mockup/patterns/filemanager/js/basepopover.js
mockup/patterns/filemanager/js/customize.js
mockup/patterns/filemanager/js/delete.js
mockup/patterns/filemanager/js/newfolder.js
mockup/patterns/filemanager/js/rename.js
mockup/patterns/filemanager/js/upload.js
mockup/patterns/filemanager/pattern.filemanager.less
mockup/patterns/filemanager/pattern.js
mockup/patterns/resourceregistry/js/overrides.js
mockup/patterns/thememapper/js/cacheview.js
mockup/patterns/thememapper/js/lessbuilderview.js
mockup/patterns/thememapper/js/rulebuilder.js
mockup/patterns/thememapper/js/rulebuilderview.js
mockup/patterns/thememapper/pattern.js
mockup/patterns/thememapper/pattern.thememapper.less
mockup/patterns/thememapper/templates/inspector.xml
mockup/patterns/upload/templates/upload.xml

- Fix setting empty ace editor instance by passing an empty text.
- Unify disabling of buttons by using setting the ``disabled`` DOM property instead using classes.
Fixes thememapper button staying disabled all the time.
- Autoformat + eslint fixes for thememapper and filemanager patterns.
- Update ``ace-builds`` to 1.2.6, which fixes IME handling in new Chrome.
Related & merge together:
https://github.com/plone/mockup/pull/754
https://github.com/plone/Products.CMFPlone/pull/1992
https://github.com/plone/plone.app.theming/pull/124

thememapper, filemanager upds

---

CHANGES.rst
mockup/patterns/structure/less/pattern.structure.less

This gave an ugly site in develoment mode when editing the loggedin bundle css.
Fixes https://github.com/plone/Products.CMFPlone/issues/1843.

Fixed path to tooltip less files.

---

CHANGES.rst
mockup/less/mixins.less
mockup/patterns/structure/js/views/tablerow.js
mockup/patterns/structure/less/pattern.structure.less
mockup/patterns/structure/templates/table.xml
mockup/patterns/structure/templates/tablerow.xml
mockup/tests/pattern-structure-test.js

- Show ineffective label in folder contents for not yet effective and published content, likewise it's done with expires.
Show effective and ineffective label styled as bootstrap badges.
- Show "Description" below title, if it's set in ``availableColumns`` and ``activeColumns`` to save some screen space.
- Add default plone color less variables for a more consistent design.
They will be overwritten by values set by Plone or integration projects.

More structure widget optimizations

---

CHANGES.rst
mockup/patterns/relateditems/pattern.js
mockup/patterns/relateditems/templates/result.xml

I wanted to customize "One level up", so I added the class name also for the top result node.
Includes also two localization fixes.

Make "One level up"-item customizable

---

CHANGES.rst
mockup/js/config.js
mockup/patterns/structure/js/views/addmenu.js
mockup/patterns/structure/js/views/app.js
mockup/patterns/structure/js/views/table.js
mockup/patterns/structure/js/views/upload.js
mockup/patterns/structure/pattern-structureupdater.js

- New pattern ``mockup-patterns-structureupdater`` to update title and description depending on the current context on Plone's folder contents page.
- Structure widget: Trigger ``context-info-loaded`` on body to be able to listen to the event outside the pattern.

New pattern mockup-patterns-structureupdater

---

CHANGES.rst
mockup/patterns/formunloadalert/pattern.js

I was annoyed by formunloadalert pattern raising errors into JS console when modals were opened.
The broken code in question was years old. I have no idea, what it is supposed to do and if it still really works: https://github.com/plone/mockup/commit/22ead2779a0897442db2977076714b92fff9ea16
Yet, I found that what was previously data('pattern-modal') is nowadays data('patternPloneModal'). I assume this change is related to making mockup Patternslib compatible. @thet might know

Fix issue where formunloadalert pattern raised initialization error for modals

---

CHANGES.rst
mockup/patterns/modal/pattern.js

For ``pat-modal``, let the ajax modal variant acquire it's ajax url when the modal is shown instead when the pattern is initialized.
This makes the modal respect a dynamically changed href attribute on a anchor tag, after it was initialized.

Resolve ajaxUrl later

---

CHANGES.rst
mockup/patterns/relateditems/pattern.js
mockup/patterns/relateditems/pattern.relateditems.less
mockup/tests/pattern-relateditems-test.js

- Make favorites container positon relative, so that the absolute positioned dropdown appears correctly.
- do not filter out already selected but folderish items in browse mode
There is one weired thing with the "do not filter out already selected but folderish items in browse mode" commit: When a folderish item is selected, it's hard to browse into this folder again. The result list always resets to another position when hovering over it. Have to investigate that.

Related Items filter/css

---

mockup/patterns/structure/js/views/tablerow.js
mockup/patterns/structure/templates/tablerow.xml
mockup/tests/pattern-structure-test.js

Followup of https://github.com/plone/Products.CMFPlone/issues/1734

Cleanup of PLIP #1734

---

CHANGES.rst
mockup/patterns/formunloadalert/pattern.js
mockup/patterns/modal/pattern.js

Merging this PR should close:
* https://github.com/plone/mockup/issues/776
* https://github.com/plone/mockup/issues/777
These were getting in the way of reasonable plone.schemaeditor operation in Plone 5.1/master, and **really need to make it into Products.CMFPlone 5.1b4, if we can**.
@thet can you take a look.

Fix two issues with form modals

---

CHANGES.rst
mockup/patterns/upload/pattern.js

Upload pattern: Fix missing plone.protect authenticator token which led to broken uploads.
Fixes: https://github.com/plone/Products.CMFPlone/issues/2076
Merge together:
https://github.com/plone/Products.CMFPlone/pull/2079
https://github.com/plone/mockup/pull/780

Upload pattern: authenticator token

---

mockup/patterns/filemanager/pattern.js
mockup/patterns/thememapper/pattern.thememapper.less

@b4oshany Small issue. If the "edited" theme is readonly, find menu actions get disabled. (Code in thememapper patterns calls disable for all button groups.) Iterating through all buttons to only enable find-menu looked complex in themepattern, so I propose simply disabling "disable" from find menu component.

Theme filemanager searching feature fixes

---

CHANGES.rst
bower.json

@b4oshany requires up-to-date jqtree version to be able to add drag and drop move support for filemanager pattern. @thet, should be upgrade this with the filemanager pattern feature pull or could be update this separately? Also, is there anything else to consider that tests on mockup pass with this pull and then we also update the resources in CMFPlone with https://github.com/plone/Products.CMFPlone/pull/2082

Pin jqtree = 1.4.1

---

CHANGES.rst
bower.json
package.json

Align bower.json versions fixes to Products.CMFPlone 5.0.x.
/cc @datakurre @b4oshany 
CMFPlone 5.0 depends on mockup 2.1.x - so updated the jqtree version in this branch - among others.

bower update 2.1.x

---

CHANGES.rst
mockup/patterns/structure/README.rst
mockup/patterns/structure/pattern-structureupdater.js

Here is some documentation on how to customize and overload the structure updater pattern.
It also applies on how to customize any pattern in general.
I've put it into mockup/mockup/patterns/structure - which doesn't follow our conventions but is probably a good place to put it to.
It's also written as .rst instead of MarkDown like the rest of mockups docs are written.
I used .rst because I know it better and I need some feedback anyways.
I'm not sure if this docs should live here or go to docs.plone.org - but I couldn't find an appropriate place there and I do not want to start a new chapter just to be able to put this documentation there....
any opinions or comments?

Add docs on how to customize the structure updater pattern

---

CHANGES.rst
mockup/patterns/relateditems/pattern.js
mockup/tests/pattern-relateditems-test.js

Related Items: Fix filtering of non-selectable and non-browsable items, so that no empty list elements are contained.
Filtering behavior is: When browsing, show only folderish or non-selected, selectable items (but non-selectable, folderish items are greyed out).
When searching, show only selectable items, which were not already selected.
This fixes an issue where it was impossible to select items when many items were filtered out.

Fix filtering of non-selectable items

---

CHANGES.rst
mockup/patterns/sortable/pattern.js

This PR fixes the drop-callback of the sortable pattern
https://community.plone.org/t/mockup-pattern-sortable-associating-a-callback-function-with-drag-and-drop-not-working-as-expected/3608
Since the pattern arguments always seem to be converted to strings, this patch looks up the method name in the global window space.
https://stackoverflow.com/questions/359788/how-to-execute-a-javascript-function-when-i-have-its-name-as-a-string

Fix callback for sortable pattern

---

CHANGES.rst
mockup/patterns/inlinevalidation/pattern.js

I've currently tested this only with dexterity objects. Probably can test with archetypes. Has Plone 5 anywhere formlib forms with this inline validation?

Queue inline validation calls

---

CHANGES.rst
mockup/patterns/sortable/pattern.js

It can still be the name of the function in the global namespace.
Fixes #808.

Restore ability from < 2.5.1 to let the ``drop`` callback be a function.

---

CHANGES.rst
mockup/patterns/structure/js/views/generic-popover.js
mockup/tests/pattern-structure-test.js

The `remove tags` input in the tags popover of the structure pattern uses a `select multiple`.
`serializeArray()` produce one object for each value selected in this input. So only the last one is saved in the data (and posted to the view).
This PR concatenate the value to data if a value with the same name is already present (with a `,`, same as how the `pat-select2` with multiple works).

Concatenate value for select multiple input in generic popover in the structure pattern

---

CHANGES.rst
mockup/patterns/structure/js/views/addmenu.js
mockup/patterns/structure/js/views/app.js
mockup/patterns/structure/js/views/table.js
mockup/patterns/structure/js/views/upload.js

Set default page icon on item row. Fixes: https://github.com/plone/Products.CMFPlone/issues/2131
Pass event data for the ``structure-url-changed`` event correctly.
Merge together:
https://github.com/plone/Products.CMFPlone/pull/2180
https://github.com/plone/mockup/pull/814

Structure pattern - pass event data for trigger events correctly.

---

CHANGES.rst
mockup/patterns/markspeciallinks/pattern.js
mockup/tests/pattern-markspeciallinks-test.js

Backport from https://github.com/plone/mockup/pull/821 so it can be included with 5.0

Mark special links: Do not mark anchors as special links. fixes gh-707

---

CHANGES.rst
mockup/patterns/tinymce/js/links.js

With the current implementation 2 kinds of elements are parsed for the anchor selction in TinyMCE
1. `a`  and `img` with either the `mceItemAnchor`  or the `mce-item-anchor` class present
2. elements set by the `anchorSelector` parameter (`h1,h2,h3` by default)
This PR changes the behavior of 1. It adds **ALL** elements with one of the classes  `mceItemAnchor`  or `mce-item-anchor` set to the list of available anchors.
The risk of breaking something should be very low. The advantage is that you can allow anchors for custom elements (with the `name` or `id` attribute) by setting the marker class.

Allow more flexible anchors in TinyMCE

---

CHANGES.rst
mockup/js/utils.js
mockup/patterns/relateditems/pattern.js
mockup/patterns/relateditems/pattern.relateditems.less
mockup/patterns/relateditems/templates/recentlyused.xml
mockup/patterns/relateditems/templates/toolbar.xml
mockup/patterns/structure/js/actionmenu.js
mockup/patterns/structure/js/views/app.js
mockup/tests/pattern-relateditems-test.js

recently used items are stored in ``localStorage``. 
note: the related PR https://github.com/plone/plone.app.relationfield/pull/21 was superseded by 
https://github.com/plone/plone.app.widgets/pull/177
merge together:
https://github.com/plone/mockup/pull/826
https://github.com/plone/Products.CMFPlone/pull/2257
https://github.com/plone/plone.app.widgets/pull/177
https://github.com/plone/plone.app.relationfield/pull/22
https://github.com/plone/plone.app.z3cform/pull/84
https://github.com/plone/Products.Archetypes/pull/102

Related Items: Add dropdown with recently added items.

---

CHANGES.rst
mockup/patterns/pickadate/pattern.js

pickadate buttons (today and delete) didn't have a type="button" attribute.
If we use a date field with this widget inside a form, we need to have that attribute, to avoid these buttons listen to form submission events.
P.S.: the file has been saved with prettier, so it looks more different in the diff. If it's a problem, i'll revert it and commit only my changes without prettier.

Add type=button to pickadate buttons to avoid form submit problems

---

CHANGES.rst
mockup/patterns/resourceregistry/js/overrides.js

The override pattern was removing the "disabled" property, but the button was being disabled by the disabled CSS class, making the buttons unusable.

Fixed resource registry controlpanel overrides tab save button

---

CHANGES.rst
mockup/js/utils.js
mockup/tests/utils-test.js

Current regex `((.|[\n\r])*)` doesn't match non ASCII characters. 
I've found that `[^]` (see also https://stackoverflow.com/a/36006948) could be simpler and better.
I experienced the problem in the wild with pat-modal and AJAX and a remote page with not ASCII characters.
This PR try to add tests that stress this problem and a fix to solve them.

Fixing problem with parseBodyTag when txt contains non ASCII chars.

---

CHANGES.rst
mockup/patterns/tinymce/js/links.js
mockup/patterns/tinymce/pattern.js
mockup/patterns/tinymce/templates/image.xml

This adds an option to the tinymce pattern to make it possible to configure the available image classes / alignment options. I want to use this on one site to provide a "full width image" option.

Make it possible to customize the available image classes

---

CHANGES.rst
mockup/patterns/structure/js/actionmenu.js
mockup/tests/pattern-structure-test.js

/@@edit specifies a browser view, which is not available for Archetypes content items.  /edit should work more generally.

Fix edit link

---

CHANGES.rst
mockup/patterns/modal/pattern.js

This reverts d06669e994f5a3:
resize/position modal again once all images are loaded,
plone/plone.app.toolbar#98
plone.app.toolbar is obsolete, and repositioning after loading each
image can get expensive. For example, if a modal contains a
DataGridField widget with reordering enabled and 20 rows, each row
contains 4 images, so the modal is repositioned 80 times.
The issue, plone/plone.app.toolbar#98, is no longer visible, so I'm
not sure if we run into other issues by removing this code.

Modal performance: don't reposition after loading each img

---

CHANGES.rst
mockup/patterns/relateditems/pattern.js

Relateditems: Raise the timeout when typing searchterms from 100 milliseconds to 500 milliseconds to prevent a too high server load.
Relateditems: Do not filter out current context.
Filtering out the current context makes sense for the related items field but it can be problematic for other use cases.

relateditems: type timeout, allow selecting current context

---

CHANGES.rst
mockup/patterns/markspeciallinks/pattern.js

For performance and security external link marked as target=_blank must be opened as rel="nopener".
More info here:
https://developers.google.com/web/tools/lighthouse/audits/noopener
https://mathiasbynens.github.io/rel-noopener/

Mark external link with rel="noopener"

---

CHANGES.rst
mockup/patterns/tinymce/js/links.js

The chosen size for an image scale was being prefilled fine for all scales, except when the chosen scale was "Original", in which case the scale was an empty string.
Because of the removed "if", the chosen scale when "Original" was used, was "Large"
Steps to reproduce:
1) Open the "Insert/edit image" in TinyMCE
2) Choose an image, and choose the "Original" scale
3) Click "Insert"
4) Click the "Insert/edit image" again for the inserted image
5) Notice the "Size" drop down will now have "Large" selected
Expected result:
"Original" should be the selected option for the "Size" drop down

Bugfix: Prefill the scale drop down when "Original" was the used scale

---

CHANGES.rst
mockup/patterns/contentloader/pattern.js

pat-contentloader: When the content which replaces the target is empty, empty the target instead of removing it.
This fixes a problem, where an empty result didn't did remove the ability to successfully replace the target for subsequent content loads.

pat-contentloader: do not remove target

---

CHANGES.rst
mockup/patterns/tinymce/less/pattern.tinymce.less

because files with relative resources were imported as with (inline) instead of (css)
https://github.com/plone/mockup/pull/832#pullrequestreview-122690361

Fix issue where webpack was unable to load TinyMCE bundle styles

---

CHANGES.rst
mockup/js/i18n.js

With this fix, country specific language codes are correctly loaded. Fixes plone/Products.CMFPlone#949
As language codes are obtained via lang property in the html tag, there is an inconsistency with Plone locales code base. For instance, Brazilian Portuguese lang attribute is pt-br, but in plone locales is referred to as pt_BR.
This code does a simple transformation on the language code so that correct translations are loaded.

Fix for loading country specific languages codes

---

CHANGES.rst
mockup/js/i18n.js
mockup/patterns/tinymce/less/pattern.tinymce.less
mockup/patterns/tinymce/pattern.js
mockup/tests/i18n-test.js

tinymce: Do not include content.min.css as part of the bundle

---

CHANGES.rst
mockup/tests/pattern-tinymce-test.js

Was not visible in PhantomJS, but happens in Chrome and FF testruns.
(before https://github.com/plone/mockup/pull/861 that is, that causes it to appear in PhantomJS too).
Was due to a form submit with no preventDefault in a testcase.
This fix should be merged before #861

Fix error when running tests: "Some of your tests did a full page reload"

---

CHANGES.rst
mockup/patterns/datatables/pattern.datatables.less
mockup/patterns/structure/js/views/table.js
mockup/patterns/structure/pattern.js
mockup/patterns/structure/templates/table.xml
mockup/patterns/tooltip/pattern.js
mockup/tests/pattern-structure-test.js

Some changes which add to previous commits:
- The column count for the datatables initialization was wrong and led to a bunch of errors.
- Datatable CSS imports need to be with (inline) option, otherwise only a CSS import directive is included which leads to 404 errors.
- The Drag & Drop status message was not very clear to me. IMO thats better (@tkimnguyen plz have a look at that change)
Two new things:
- pat-structure: Use more tooltips in the actions menu.
- pat-structure: Move breadcrumbs out of folder contents table.

Structure fixes

---

CHANGES.rst
mockup/less/docs.less
package-lock.json

See before and after comparison screenshots:
Note the overflow of the description of the "Textarea MimeType Selector" pattern
No need to waste vertical space on mobile

Improve docs styles

---

CHANGES.rst
mockup/patterns/resourceregistry/js/fields.js
mockup/patterns/resourceregistry/js/registry.js

- pat-resourceregistry:
- Add input fiels for ``merge_with``, ``last_compilation``, ``jscompilation`` and ``csscompilation``.
- Add ``load_async`` and ``load_defer`` options.
the resource registry looks now like: 
Merge:
https://github.com/plone/Products.CMFPlone/pull/2644
https://github.com/plone/mockup/pull/879
https://github.com/plone/plone.app.upgrade/pull/186

pat-resourceregistry: Add load_async and load_defer options.

---

mockup/patterns/moment/pattern.js
news/894.fix

- Avoid leaking lazyLoadMomentLocale to global namespace
- Fix bug by not lower casing mockup-i18n's currentLanguage
- Fix bug on IE11 due to lack of support for 'includes'

Fix bugs on Moment.js lazy loading

---

mockup/patterns/toolbar/pattern.toolbar.less
news/897.bugfix

Fix the scrollbar always present in the toolbar

---

mockup/patterns/structure/less/pattern.structure.less
news/895.bugfix

Fix alignment of the default page objects in the structure pattern

---

mockup/patterns/inlinevalidation/pattern.js
news/903.fix

The way I am fixing this issue, is by 
1) clone the original form
2) remove any ``<input type="file">`` from it
3) submit this cloned form instead
If an error comes from the validation, it will be rendered in the original form

pat-inlinevalidation: Avoid submitting files

---

mockup/patterns/structure/less/pattern.structure.less
news/895.bugfix
news/908.bugfix

instead of fixing it on the page.

Position the asterisk inside its parent,

---

news/913.feature
package.json
yarn.lock

Updated versions:
<hr>
I postponed `karma-sauce-launcher` for now because it [failed installing](https://travis-ci.org/plone/mockup/jobs/549814555) `selenium-webdriver@4.0.0-alpha.4` with "incompatible linux platform" for `fsversion@1.2.9`: 
```
yarn install v1.3.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
error selenium-webdriver@4.0.0-alpha.4: The engine "node" is incompatible with this module. Expected version ">= 10.15.0".
error Found incompatible module
```
<hr>
Finally we may include Sinon too if we solve the problem reported …

Upgrade testing dependencies: Karma and Mocha

---

mockup/patterns/structure/js/views/textfilter.js
news/932.bugfix

Structure pattern: Escape special characters when filtering

---

mockup/patterns/tinymce/pattern.js
news/867.bugfix

This uses the ui_container configuration option in TinyMCE to anchor the position of menus to the parent modal.
https://github.com/tinymce/tinymce/commit/7fd61eeac61e9a88dfe8ed3c4c0398b5ee0328e2
Closes #867

TinyMCE: fix positioning of sub-menus in a modal

---

mockup/patterns/querystring/pattern.js
news/939.bugfix

pat-querystring: Fix path widget for old dashed UIDs (plone.uuid < 1.0.2)

---

.travis.yml
mockup/Gruntfile.js
mockup/js/ui/views/button.js
mockup/js/utils.js
mockup/patterns/structure/js/actions.js
mockup/patterns/structure/js/views/app.js
mockup/patterns/structure/js/views/paging.js
mockup/patterns/structure/js/views/table.js
mockup/patterns/structure/js/views/textfilter.js
mockup/patterns/structure/less/pattern.structure.less
mockup/patterns/structure/templates/status.xml
mockup/patterns/structure/templates/table.xml
mockup/tests/pattern-structure-test.js
news/937.feature
news/938.feature
news/943.bugfix

Structure pattern:
- Show statusmessage with "Clear filter" button when filters are applied.
- Show visually if a filter is set.
- Allow multiple status messages.
- Display toolbar a bit compacter.
- Instead of clearing the filter when changing the path (initial approach from first commit) now there is a status message shown with a "Clear filter" button in it. For this to work it was necessary to allow multiple status messages. The "Clear filter" status message must always be present while other status messages must still be possible.
That way it should be very obvious that the current view is filtered.
- If a text filter is set, the filter input has a blue border.
- if a querystring is set, the magnifier icon has a blue background.
- The status messages look a bit nicer.
Applied filter: …

Structure pattern: Filter UI improvements, etc.

---

mockup/patterns/tinymce/js/links.js
mockup/patterns/tinymce/pattern.js
mockup/patterns/tinymce/templates/image.xml
mockup/tests/pattern-tinymce-test.js
news/911.feature

In the TinyMCE Image dialog:
- Adds an option for image captioning support from the description of the image ("Show Image Caption from Image Description") (uses an plone.outputfilters filter),
- Adds an textfield for manual image captions,
- Wraps the image in a ``<figure>`` tag and adds a ``<figcaption>`` if "Show Image Caption from Image Description" is not checked and the manual caption is present.
- If no caption is present, only the image tag is added.
Re-adds image caption support, which was present until Plone 5.
Screenshot:
Merge:
https://github.com/plone/mockup/pull/911
https://github.com/plone/plone.staticresources/pull/30
https://github.com/plone/Products.CMFPlone/pull/2887
https://github.com/plone/plone.outputfilters/pull/36

Add image caption support

---

mockup/patterns/tinymce/pattern.js
news/945.bugfix

because there might be more than one TinyMCE in the DOM.

Generate a random id and append it to the container_id

---

mockup/patterns/structure/templates/actionmenu.xml
news/965.bugfix

Fixes #965 
@codesyntax
@codesyntax/plone
@ionlizarazu

add missing aria-labels to action icons

---

mockup/patterns/structure/js/views/app.js
news/963.bugfix

Fixes #963 
With these changes each popover is rendered just after its corresponding button, allowing to tab-navigate to them just after clicking each button and improving their accessibility
@ionlizarazu

add popover after each button

---

mockup/patterns/structure/less/pattern.structure.less
mockup/patterns/tinymce/js/links.js
mockup/patterns/tinymce/pattern.js
mockup/patterns/tinymce/templates/image.xml
mockup/patterns/tinymce/templates/link.xml
news/910.bugfix
news/986.bugfix
yarn.lock

See the screenshot of the issue at
https://github.com/plone/Products.CMFPlone/issues/3120#issuecomment-646523670

Fix Upload tab in TinyMCE Image showing [object Object]

---

package.json
yarn.lock

Fix multiple versions or wrong version of some packages when we switched from bower to yarn.
Bower dependencies installation was flat by design. With npm or yarn, this is not the case, so we need to be extra careful.

Fix duplicate versions

---

mockup/patterns/resourceregistry/pattern.resourceregistry.less
news/990.bugfix

See https://github.com/plone/Products.CMFPlone/issues/1111

Fix CSS issue on "Pattern options" tab in Resource Registries

---

mockup/js/ui/views/anchor.js
mockup/js/ui/views/button.js
mockup/patterns/filemanager/pattern.filemanager.less
news/996.bugfix

This fixes https://github.com/plone/Products.CMFPlone/issues/2296

Fix regression for disabled state of action buttons in folder contents

---

mockup/patterns/upload/templates/preview.xml
news/1000.bugfix

This fixes https://github.com/plone/plonetheme.barceloneta/issues/204
and https://github.com/plone/Products.CMFPlone/issues/2533

Fix filename overlapping the remove button in the Upload dialog

---

mockup/js/ui/views/popover.js
mockup/less/popover.less
mockup/patterns/structure/js/views/app.js
mockup/patterns/structure/less/pattern.structure.less
news/1002.bugfix

My fix https://github.com/plone/mockup/commit/a6fa639b9e80ec04d9143bf451e73fd51d6ff0ae for https://github.com/plone/Products.CMFPlone/issues/3124 introduced regressions with Plone toolbar and navigation tabs that apparently was fixed before, see https://github.com/plone/Products.CMFPlone/issues/2307
This PR revert my previous fix and add a new placement mode "bottom-right' for popover that I applied to the 'Configure display column' popover

Fix folder contents z-index issues with toolbar and nav tabs

---

mockup/patterns/toolbar/pattern.toolbar.less
news/1003.bugfix

This fixes https://github.com/plone/Products.CMFPlone/issues/1972
on Chrome
Before:
After:

Fix toolbar menus missing checkmark on some browsers

---

mockup/patterns/structure/js/actionmenu.js
mockup/patterns/structure/pattern.js
mockup/tests/pattern-structure-test.js
news/1005.bugfix

Fixes https://github.com/plone/Products.CMFPlone/issues/2700
Together with https://github.com/plone/plone.app.content/pull/208

respect default_page_types in actionmenu if folder_contents

---

mockup/patterns/toolbar/pattern.toolbar.less
news/1009.bugfix

This fixes https://github.com/plone/Products.CMFPlone/issues/3163
The bug was already present in Safari before https://github.com/plone/mockup/pull/1003 changes, but the bug surfaced on Chrome and Firefox with the changes in https://github.com/plone/mockup/pull/1003

Put back content type icons in the Add new... menu.

---

mockup/patterns/modal/pattern.js
news/11.bugfix

Fixes #11.
Working on modal pattern:
- ARIA and roles attributes
- focus trap within modal
- focus handling in general about modal
- re-assign focus on modal opening link when closing
- close on click

[a11y] focus handling in modal pattern

---

news/1022.feature
package.json
patches/select2.patch

Closes: https://github.com/plone/mockup/pull/912
pat-select2: Patch Select2 version to include UI improvements from: https://github.com/collective/select2-3.5.3-custom#mrtango-improve-relateditems-ux
Related to:
https://github.com/plone/mockup/pull/889
Together with:
https://github.com/plone/mockup/pull/912
https://github.com/plone/plone.staticresources/pull/28

Related Items: Add customized Select2 version

---

mockup/patterns/toolbar/pattern.js
news/3191.bugfix

Main issue: this fixes the links in the plone toolbar becoming outdated when one navigates more than once in in the folder contents view. 
But wait, there's more...
What still is very strange and I think unwanted is that the toolbar updating is done twice.  And it's not only the toolbar, for every navigation click in folder_contents, 3 ajax calls are made twice to the backend for:
* `@@render-toolbar`  (toolbar itself)
* `@@fc-contextInfo` (actions in the toolbar)
* `@@getVocabulary`   (folder_contents main table)
When I inspect the registered event handlers on the body element in the Firefox devtools, the toolbar structure-changed event is present twice , once from jquery and once from DOM2|bubbling, but I have no clue if this causes the double refresh of the toolbar. 
Also: another …

Fix toolbar being updated only on the first navigation action

---

mockup/patterns/toolbar/pattern.js
news/3191.bugfix

They are only updated when in folder contents on the first navigation action
Fixes Products.CMFPlone #3191. Forward port from 3.x branch.
Also clean up previous closetoolbarsubmenu's event handler before re-adding #3191

Fix plone toolbar action links not being updated

---

mockup/patterns/structure/js/views/app.js
mockup/patterns/structure/js/views/table.js
mockup/patterns/structure/js/views/textfilter.js
mockup/patterns/structure/pattern-structureupdater.js
news/3203.bugfix

Triggered by the textfilter being reset which initialises the collection pager and does a new full refresh.
Also un-reregister more eventhandlers in structure pattern

prevent double xhr requests with folder navigation in structure pattern

---

mockup/js/grunt.js
mockup/less/base.less
mockup/less/docs.less
mockup/less/filemanager.less
mockup/less/resourceregistry.less
mockup/less/structure.less
mockup/less/widgets.less
mockup/patterns/querystring/pattern.querystring.less
mockup/patterns/relateditems/pattern.relateditems.less
mockup/patterns/structure/less/pattern.structure.less
package.json

Also updates the fonts to bootstrap3 paths. 
Renames bootstrap to bootstap3 as done by @agitator here: https://github.com/plone/plone.staticresources/commit/e7959733fc70baa442faf3a5385a417359ce1720
@thet Would this work? For me it fixes compiling form scratch.

Update bs3 paths

---

MANIFEST.in

The coredev buildout took very long for me.
Trying it manually, `python setup.py egg_info` took five minutes.
Problem was that I had a large `mockup/node_modules` directory.
This was pruned in `MANIFEST.in`, so it never ended up in the release.
But is *was* first included before being pruned, and this took extremely long.
For explanation of what happens, see the [packaging docs](https://packaging.python.org/guides/using-manifest-in/) and look for this line: "Commands are processed in the order they appear in the MANIFEST.in file."
For the mockup case it meant:
- `recursive-include mockup *.js`: include all javascript files, also when found in `mockup/node_modules`.
- `prune mockup/node_modules`: throw them away again.

Fix manifest to not include node_modules, even when later removed.

---

1041.bugfix
mockup/patterns/structure/js/views/addmenu.js
mockup/patterns/structure/js/views/table.js
mockup/patterns/structure/js/views/upload.js
mockup/patterns/structure/pattern-structureupdater.js

Do only remove the correct event listener on ``context-info-loaded`` before adding a new one.
Fixes a problem where the current path was not updated for the upload popup when changing paths.
Fixes: #1016
Refs: #1028, #1030, #1039

Correctly update the context info when changing paths.

---

mockup/less/base.less
mockup/patterns/querystring/pattern.querystring.less
mockup/patterns/relateditems/pattern.relateditems.less
mockup/patterns/structure/less/pattern.structure.less
news/1042.bugfix

Remove fonts from patterns to avoid multiple inline includes.
Glyphicons are removed as less-includes from patterns.
In Plone we add two more bundles to include the icons: https://github.com/plone/plone.staticresources/pull/131
In Mockup docs the bootstrap.less is included, so the demo patterns still have their icons: https://github.com/plone/mockup/blob/3.x/mockup/less/docs.less#L5

Remove fonts from patterns to avoid multiple inline includes.

---

news/1130.feature
src/pat/tinymce/js/links.js
src/pat/tinymce/templates/image.xml
src/pat/tinymce/tinymce.js

This allows us to enable image zoom when inserting an image with TinyMCE. It will only add a CSS class zoomable, which can be used by addons or custom JavaScript to make the image zoomable.

pat-tinymce: Add enable image zoom option

---

src/pat/structure/js/views/table.js

This slightly reduces the complexity of the code for waiting for table row rendering end.
It basically removes one event handler.

Simplify structure tablerow

---

package.json
src/pat/structure/js/actionmenu.js
src/pat/structure/js/views/actionmenu.js
src/pat/structure/js/views/app.js
src/pat/structure/js/views/selectionwell.js
src/pat/structure/js/views/table.js
src/pat/structure/js/views/tablerow.js
src/pat/structure/templates/selection_item.xml
yarn.lock

I've updated Backbone to latest 1.4.1 (released 2022-02-26) today which was surprisingly easy. Main change is the `ActionMenuView` with the `categorizedMenuOptions` which has to be refactored because the `events` are called before `initialize` now via `delegateEvents`.
Don't forget to `yarn install` again, when using this branch!
~~There's one issue left: `ActionMenu` is rendered twice in the column on the very first call. when moving, paging etc. the table is rendered correctly. Maybe someone has an idea why?~~ fixed!
In another step I try to update `backbone.paginator` to 2.0.4 but that needs rewriting of our `ResultCollection` to the new `PageableCollection` and its API.
/cc @frapell @thet

Backbone 1.4.1 update

---

src/index-bootstrap.js
src/index-jquery.js
src/index.js
src/patterns.js
webpack.config.js

Here I register jQuery and Bootstrap globally directly in the main bundle - making the jquery and bootstrap bundles obsolete.
jquery and bootstrap are available before DOMContentLoaded.
This increases the initial bundle size significantly:‌ from 93k to 269k.
Some thoughts:
- We could split out Bootstrap into a own bundle without module federation and provide it optionally (but we're using some bootstrap js in mockup already, so there will be some code duplication).
- We could provide two alternative main bundles - one with the global registrations and one without. Integrators can then choose which one they use.
- We don't care about the bundle size - < 300k are not that awful much in the end...
- For customized sites we can always build our own bundle, optimize it for size and not use the …

Register jQuery and Bootstrap globally - alternative approach

---

src/pat/tinymce/js/links.js

Came accross this in robot tests: When opening the "insert image" modal while an "internal link" is selected, the modal gets stuck ... checking if the linkType of the current selected dom matches the modal linkTypes fixes that.
see https://jenkins.plone.org/job/pull-request-6.0-3.8/1628/testReport/Products.CMFPlone.tests.test_robot/RobotTestCase/Scenario_A_page_is_opened_to_edit_in_TinyMCE/

Fix `linkType` mismatch in link/image modal

---

src/pat/querystring/querystring.js

Do not close modal if querystring criteria is removed

---

src/pat/controlpanels/schemaeditor--implementation.js

Fix adding fields to fieldsets, and drag and drops between fieldsets. 
Prevent adding fields to fieldsets from behaviors.
fixes gh-1201

Fix schemaeditor

---

src/pat/select2/select2.js

Fixes #994. Similar to #1211 we need to explicitly set the language and load the language js file
Basque:
German
Spanish:

fix(pat-select2): load language files

---

src/pat/tinymce/tinymce.js

After some debugging I have noticed that although the correct language js was being loaded, we need to explicitly set the language we are using in tiny options.
This way the correct language js is applied and the editing interface shows translated. See:
German
Spanish 
Basque
Fixes #1209 and https://github.com/plone/Products.CMFPlone/issues/3619

fix(pat-tinymce): set the language in tiny options

---

src/pat/relateditems/relateditems.js
src/pat/select2/select2.js

Alternative approach to: https://github.com/plone/mockup/pull/1214
Fixes: https://github.com/plone/mockup/issues/1205
@mauritsvanrees based on your analysis I built an alternative, more appropriate approach to the sorting issue.
``initializeOrdering`` is called after ``initializeSelect2`` and also initializes existing items without a ``change`` event.
I added you as co-author.
@mauritsvanrees Please review, test and eventually approve.

Fix select2/relateditems sorting issue

---

src/pat/relateditems/relateditems.js

This fixes https://github.com/plone/mockup/issues/1221

fix(pat relateditems): call .stopPropagation on events for breadcrumbs links

---

src/pat/recurrence/recurrence.js
src/pat/recurrence/templates/form.xml

Editing weekly weekdays was broken due to array index/value mismatch in input name.
This also fixes reloading occurrence when changeing the weekdays checkboxes.

Fix editing weekly weekdays

---

src/pat/livesearch/livesearch.js

This commit remove `d-none` from resultsClass. After the setting `$enable-important-utilities:  false !default;` has been added to barceloneta scss, the d-none class can be overridden by the style attribute value `display: none`. For themes not using `!important` like default bootstrap, this doesn't works. Here, pat-livesearch starts with d-none and apply at init the style attribute value `display: none`.  This means that this works only with  `$enable-important-utilities:  false !default;` . Removing d-none from the list of class, make using display: block (to show the results) work in both cases. `d-none` here is useless anyway because the pattern hides the block in the init function. I've tested it with barceloneta theme (`$enable-important-utilities:  false !default;` ) and a custom …

toggle d-none instead of using the style attribute to show/hide the results

---

src/pat/tinymce/tinymce--implementation.js

@petschki I have verified, by creating a Mosaic tile with 2 RichText fields, with an edit view, instead of inline rendering.
I can confirm that `self.$el.parents(".plone-modal-dialog");` is always length 0, so that code is no longer used.
Both tinymce work fine
I created this test product, and included it in buildout.coredev along with mosaic to test https://github.com/frapell/mosaic.tiles

maint(pat tinymce): Cleanup old code no longer needed. closes gh-1198

---

src/pat/recurrence/recurrence.js
src/pat/recurrence/templates/form.xml

fixes #1266 
This is also partly a code cleanup of the old jquery-recurrencewidget approach. The main fix is to save the parsed `RRULE` object to the `textarea['ical']` attribute instead of the jquery form ... this gives us a sane state during editing the recurrence widget multiple times.

Fix recurrencewidget to initialize saved value correctly and fix RDATE and EXDATE editing

---

src/pat/relateditems/relateditems.js
src/pat/select2/select2.js
src/pat/select2/select2.test.js

A select[multiple] field without the multiple pattern option set is no longer replaced with a input[type=hidden].
This fixes a problem in pat-querystring where switching from one criteria to another duplicated the Select2 fields. Select2 deals just fine with select[multiple] fields. The replacement part should be evaluated for validity and eventually removed for a future Mockup release.

fix(pat-select2): Do not replace multi select fields for pat-querystring.

---

src/pat/recurrence/recurrence.js

This PR fixes 3 specific use cases with the recurrence pattern:
1. "Repeats Monthly" -> "The [first, second, third, fourth, last] [Sunday, Monday......Friday] of the month"
After saving, and then re-opening the recurring "Repeat popup", the date would be blank
2. "Repeats Yearly" -> "The [first, second, third, fourth, last] [Sunday, Monday......Friday] of [January,.... December]"
After changing these values, the Selected dates weren't updating
3. "Repeats Yearly" -> "The [first, second, third, fourth, last] [Sunday, Monday......Friday] of [January,.... December]"
After saving, and then re-opening the recurring "Repeat popup", the date would be blank

fix(pat recurrence): Fixes for 'Repeat on' for Yearly and Monthly options

---

src/pat/textareamimetypeselector/textareamimetypeselector.js

This should fix TinyMCE in modals not showing up (see https://github.com/plone/plone.app.mosaic/issues/528)

Async initialization of textareas

---

src/pat/tinymce/tinymce--implementation.js

Fixes #1116 
Add `urlconverter_callback` and skip converting external urls.
IMPLEMENTATION NOTES:
This is a quick and rough solution which checks if inserted url starts with "http" ... it would be more solid if we query the inserted element and check for the `dataset.linktype` value, but right now I have no clue, how to get the element in the callback.

Fix TinyMCE external url handling

---

src/pat/upload/upload.js

this fixes https://github.com/plone/Products.CMFPlone/issues/3814

prevent duplicate initialization of the dropzone.

---

src/pat/relateditems/relateditems.js

fixes #1319 
NOTE: absolutely no clue why this makes a difference `this.$el` and `$(this.el)` but I changed it back like it was before and it works again. See commit https://github.com/plone/mockup/commit/d8f2daa9f45b6805dd9f35e791437e04bce47267#diff-0372046d8d03fc963bb3d1bedcb015a6eebdcd9cd11cfaf9d604690ba2319434L461-R458

Fix tinymce link/image modal with current selection

---

src/pat/structure/structure.scss

Fix sticky position of `pat-structure` toolbar when edit toolbar is on top

---

src/pat/tinymce/js/links.js

fix(pat relateditems): Import Select2 module before calling it when not yet initialized

---

src/pat/relateditems/relateditems.scss

There's an ugly border inside the TinyMCE modals:
left updated <> right current

Fix `pat-relateditems` styling when inside a modal.

---

src/pat/tinymce/js/links.js
src/pat/tinymce/tinymce--implementation.js

Call link/image plugins on the correct tiny6 instance

---

src/pat/tinymce/js/links.js

fixes https://github.com/plone/Products.CMFPlone/issues/3910

Fix duplicated image node when updateing already inserted image. [5.1.x]

---

src/pat/recurrence/recurrence.js

Fix comparisons between different dates formats

---

src/pat/relateditems/relateditems.scss
src/pat/structure/structure.scss
src/pat/upload/upload.scss
webpack.config.js

Begin work on SASS 1.79 compatibility.
Ref:
https://github.com/twbs/bootstrap/issues/40849
https://github.com/twbs/bootstrap/pull/40865
https://github.com/twbs/bootstrap/pull/40864
IIRC (worked on that some days ago) this is not really silencing the deprecation warnings from SASS.
Probably pinning SASS to something before 1.79 is better (`resolveDependencies`).

SASS 1.79 compatibility

---

README.md
src/pat/contentbrowser/contentbrowser.js
src/pat/contentbrowser/src/App.svelte
src/pat/contentbrowser/src/ContentBrowser.svelte
src/pat/contentbrowser/src/ContentStore.js
src/pat/contentbrowser/src/Favorites.svelte
src/pat/contentbrowser/src/RecentlyUsed.svelte
src/pat/contentbrowser/src/SelectedItems.svelte
src/pat/contentbrowser/src/utils.js
src/pat/querystring/querystring.js

`pat-contentbrowser` fixes

---

src/pat/contentbrowser/src/ContentBrowser.svelte
src/pat/contentbrowser/src/SelectedItems.svelte

`pat-contentbrowser` UI fixes

---

src/pat/modal/modal.js

fixes https://github.com/plone/Products.CMFPlone/issues/3969

Fix focus trap when modal form is reloaded with validation errors

---

src/pat/contentbrowser/src/ContentBrowser.svelte

- use the title of content object as label of the select button
- enable a bs tooltip with the path info of selected contentobject
the old behavior was "display the path", now "display the title" and show the path in a tooltip

pat contentbrowser: ui improvements for select button in toolbar

---

src/pat/structure/templates/paging.xml

This trivial PR intends to fix https://github.com/plone/mockup/issues/1412 and https://github.com/plone/Products.CMFPlone/issues/3591 by checking that `totalPages` is zero and setting it to one.

Show 'Page 1 of 1' instead of 'Page 1 of 0'.

---

package.json
src/pat/contentbrowser/README.md
src/pat/contentbrowser/contentbrowser.js
src/pat/contentbrowser/src/App.svelte
src/pat/contentbrowser/src/RecentlyUsed.svelte
src/pat/contentbrowser/src/SelectedItem.svelte
src/pat/contentbrowser/src/SelectedItems.svelte
yarn.lock

This registers `SelectedItem` component with `@plone/registry` to make it overridable.

`pat-contentbrowser` component registry

---

src/pat/contentbrowser/contentbrowser.js
src/pat/contentbrowser/src/ContentBrowser.svelte
src/pat/contentbrowser/src/utils.js

when deeply nested folders are browsed.

`pat-contentbrowser`: Fixed preview and upload column width

---

src/pat/select2/select2.js

fix the generated filename for language files in select2

fix language identifier for language file

---

src/pat/contentbrowser/src/App.svelte

Add multilanguage container types to `browseableTypes`

---

src/pat/contentbrowser/src/ContentBrowser.svelte

fixes #1443 
in action:
https://github.com/user-attachments/assets/5ef7c070-3ad1-4b36-ad13-85a6670f6ed0
Note:
the `basePath` commit is related to this issue https://github.com/plone/Products.CMFPlone/pull/4134

Improve `pat-contentbrowser` upload experience

---

src/pat/autotoc/autotoc.js
src/pat/autotoc/autotoc.test.js

this selector checks the mutlicheckbox widget for required mutliselection fields

Show required indicator for tabs with reuqired multicheckbox fields

---

.github/workflows/docs.yml
.github/workflows/test.yml
package.json

This updates the "engines" field of package.json which is a standard field as specified here: https://docs.npmjs.com/cli/v7/configuring-npm/package-json#engines
Mockup would work with lower versions of Node also - e.g. Node version 18, but "22" is the current LTS version.
Related:
https://github.com/Patternslib/dev/pull/50
https://github.com/Patternslib/Patterns/pull/1252
https://github.com/plone/mockup/pull/1465
https://github.com/plone/plone.app.mosaic/pull/634

maint: Update the compatible node version to the current LTS version.

---

src/pat/tinymce/tinymce--implementation.js

I was scratching my head for a while what this `importcss_file_filter` is for. Don't scratch yours!
There is intentionally no conventionalcommits compatible commit message as I think this change should not go into the changelog.
https://github.com/plone/mockup/pull/1467
https://github.com/plone/Products.CMFPlone/pull/4184

pat-tinymce: Document, what the importcss_file_filter is for.

---

src/pat/autotoc/autotoc.js
src/pat/autotoc/autotoc.scss
src/pat/autotoc/autotoc.test.js

This fixes first part of the [plone/Products.CMFPlone#4106](https://github.com/plone/Products.CMFPlone/issues/4106)
This change updates the markup and behavior of the AutoTOC to make it more compatible with Bootstrap's tab component. Key changes:
- Moves all fieldset elements inside a tab-content parent element.
- Replaces anchor (<a>) tab triggers with Bootstrap-compatible <button> elements, utilizes data-bs-toggle, data-bs-target, and other related attributes.
- Adds appropriate aria attributes for accessibility and correct tab behavior.
- Updates tab-click handling to use Bootstrap's tab JavaScript API, replacing the previous custom logic.

Make Autotoc tab markup compatible with Bootstrap

---

src/pat/tinymce/tinymce--implementation.js

- fix to load the chunk files for init the plugins correctly
- enable the Plugins "help" and "emoticons" in the Tinymce Controlpanel under "Plugins and Toolbar"
- in the "menu" config enable emoticons and change the entry to:
```
"insert": {
"title": "Insert",
"items": "link media | template hr | emoticons"
},
``` 
- in the "menubar" config enable the help plugin and change the entry to:
```
edit table format view insert help
```

fix(pat tinymce): init plugins "help" and "emoticons"

---

src/pat/contentbrowser/src/ContentStore.js

 fix `pat-contentbrowser` physicalPath generation when a Plone site is in a sub folder structure

---

src/pat/contentbrowser/src/ContentStore.js
src/pat/contentbrowser/src/utils.js

We've got `414 too long URL` errors when there are many items in a relationlist field. 
Additional Fix: the selected items got cut to 100 items (batchsize) after saving/re-editing ... this is fixed here too.

Use POST request for quering selected items
