mockup/js/i18n-wrapper.js, mockup/js/i18n.js, mockup/tests/i18n-test.js
This refs plone/plone.app.widgets@4b397c3
=> jsi18n -> plonejsi18n

CHANGES.rst, mockup/patterns/resourceregistry/js/builder.js
=> Fix less variable overrides by executing less-modify.js between the build and saving

mockup/patterns/structure/js/views/actionmenu.js
refs plone/Products.CMFPlone#424
=> fix param passed when setting default page from action menu in structure

mockup/js/bundles/structure.js, mockup/patterns/autotoc/pattern.js, mockup/patterns/modal/pattern.js, mockup/patterns/select2/pattern.js, mockup/patterns/tinymce/js/links.js, mockup/tests/pattern-modal-test.js
See #483 
These packages were also modified for this change and will need to be merged as well:
* Products.CMFPlone https://github.com/plone/Products.CMFPlone/pull/442
* plone.app.contentmenu https://github.com/plone/plone.app.contentmenu/pull/9
* plone.app.contentrules https://github.com/plone/plone.app.contentrules/pull/12
* plone.app.dexterity https://github.com/plone/plone.app.dexterity/pull/154
* plone.app.layout https://github.com/plone/plone.app.layout/pull/42
* plone.app.portlets https://github.com/plone/plone.app.portlets/pull/48
* plone.app.theming  https://github.com/plone/plone.app.theming/pull/42
* plone.schemaeditor  https://github.com/plone/plone.schemaeditor/pull/23
* plonetheme.barceloneta https://github.com/plone/plonetheme.barceloneta/pull/15
=> Pat modal rename

mockup/patterns/tinymce/js/links.js, mockup/patterns/tinymce/pattern.js, mockup/patterns/tinymce/templates/image.xml, mockup/patterns/upload/pattern.js
With these changes you can add/upload an image by simply pasting it from the clipboard with ctrl-v.
I think this is incredibly useful when adding screenshots.
=> allow pasting/uploading images from clipboard

mockup/js/config.js, mockup/patterns/texteditor/pattern.js
Ace now looks in the correct location to find it's support files, and loads them as needed (as per the suggestion of Ace's developers).
=> Fixed issue with Ace loading files needed for syntax highlighting

mockup/patterns/thememapper/pattern.js
Added translation capability for all the thememapper buttons.
=> Added translating

mockup/patterns/filemanager/js/upload.js, mockup/patterns/filemanager/pattern.js, mockup/patterns/texteditor/pattern.js, mockup/patterns/thememapper/pattern.js, mockup/patterns/thememapper/pattern.thememapper.less, mockup/patterns/upload/pattern.js, mockup/patterns/upload/templates/upload.xml
Adds an upload button to the thememapper interface. Also adds a view to handle the uploads correctly.
=> Thememapper uploads

mockup/patterns/filemanager/pattern.js, mockup/patterns/thememapper/pattern.js, mockup/patterns/thememapper/pattern.thememapper.less
The thememapper while now appear in "inspector mode" when viewing a filesystem theme. Pictures will now be scaled properly within the editor window, preventing them from overflowing. Editor tabs will now shrink somewhat when they start to stack in the editor window.
=> Inspector mode

mockup/patterns/filemanager/pattern.js, mockup/patterns/thememapper/js/rulebuilder.js, mockup/patterns/thememapper/js/rulebuilderview.js, mockup/patterns/thememapper/pattern.js, mockup/patterns/thememapper/pattern.thememapper.less, mockup/patterns/thememapper/templates/inspector.xml, mockup/patterns/thememapper/templates/rulebuilder.xml, mockup/tests/pattern-thememapper-test.js
Converted Plone 4.3 diazo rule builder to work in thememapper pattern. Moved the RuleBuilder class into it's own file, separate from the Thememapper, and created a new popover view to display it. 
Also @vangheem *FINALLY* fixed the infamous "2000 error per minute" scrolling bug in the Ace editor. 
Added in a basic testing setup for the thememapper.
=> Rulebuilder

CHANGES.rst, mockup/patterns/structure/js/views/table.js, mockup/patterns/structure/less/pattern.structure.less, mockup/patterns/structure/templates/table.xml, mockup/tests/pattern-structure-test.js
=> rename structure "breadcrumbs" class to "fc-breadcrumbs" to prevent name clash

mockup/patterns/querystring/pattern.js
=> fix mockup pattern querystring, for multible items in multiselects

mockup/patterns/resourceregistry/pattern.resourceregistry.less
https://github.com/plone/Products.CMFPlone/issues/618
=> Fix obscured resource registry tabs

CHANGES.rst, mockup/patterns/structure/js/views/tablerow.js, mockup/patterns/structure/less/pattern.structure.less, mockup/patterns/structure/templates/tablerow.xml, mockup/tests/pattern-structure-test.js
This is to address https://github.com/plone/Products.CMFPlone/issues/524
Here is a screenshot:
Thoughts?
=> show quick edit/view for items in structure row

CHANGES.rst, mockup/patterns/structure/js/views/app.js, mockup/patterns/structure/less/pattern.structure.less
=> remove add menu from structure as we will rely on toolbar add menu

CHANGES.rst, mockup/patterns/tinymce/js/links.js, mockup/patterns/upload/pattern.js, mockup/patterns/upload/templates/upload.xml
Automatically go to uploaded selection so it is obvious for a user what is the next step after uploading a file/image and fix issue where you could upload more than one image/file in dialog.
=> better interaction with insert uploaded image/link in tinymce

CHANGES.rst, mockup/patterns/filemanager/pattern.js
The filemanager will now reopen a file to the same line/position as when the file was last closed.
=> Filemanager will now reopen files to the same line

CHANGES.rst, mockup/patterns/pickadate/pattern.js, mockup/patterns/querystring/pattern.js
Fixes for the pickadate and querystring patterns to properly update values and get created properly if there is existing data
=> Collections fixes

CHANGES.rst, mockup/patterns/filemanager/pattern.js, mockup/patterns/thememapper/js/cacheview.js, mockup/patterns/thememapper/js/lessbuilderview.js, mockup/patterns/thememapper/pattern.js
Added a button to the thememapper that invalidates the site's theme caching, forcing a reload.
=> Cachebutton

CHANGES.rst, mockup/patterns/structure/js/views/generic-popover.js
This is part of the Linkintegrity-PLIP https://github.com/plone/Products.CMFPlone/issues/698
=> improvements to dynamic popover content handling

mockup/patterns/upload/less/pattern.upload.less
a fixed width of 600px is too wide for the tinymce dialogs
=> replace width with max-width

mockup/patterns/texteditor/pattern.js
otherwise things like this happens
'200' + 25 = '20025'
=> parse to int before doing math

mockup/patterns/upload/pattern.js
https://github.com/plone/mockup/commit/2b843802149986b7bb09e25abf1ed3e63f17e3e0
=> fix case where file could be undefined

CHANGES.rst, mockup/patterns/resourceregistry/pattern.resourceregistry.less
closes https://github.com/plone/Products.CMFPlone/issues/886
=> Issue 886 - Fix buttons positions on resource registry

mockup/patterns/formautofocus/pattern.js
=> Make formautofocus pattern work again.

CHANGES.rst, mockup/patterns/querystring/pattern.js
=> fix: set widgets values for querystring pattern

mockup/patterns/autotoc/pattern.js, mockup/patterns/tinymce/js/links.js, mockup/tests/fakeserver.js, mockup/tests/pattern-tinymce-test.js
this adds a test for uploading an image and fixes the problem
that after uploading the file the dialog nolonger changes to internal link
=> Imageuploadtest

mockup/patterns/tinymce/js/links.js
=> automatically upload image/file when clicking on insert

CHANGES.rst, mockup/patterns/resourceregistry/pattern.resourceregistry.less
(closes plone/Products.CMFPlone#1141)
=> Fix flaky behavior of Resource Registries buttons 

CHANGES.rst, mockup/patterns/relateditems/pattern.js, mockup/tests/json/queryStringCriteria.json
Should be merged together with pull requests in other packages.
Central issue: https://github.com/plone/Products.CMFPlone/issues/1040
=> Use selection.any in querystring pattern.

CHANGES.rst, mockup/patterns/querystring/pattern.js, mockup/patterns/querystring/pattern.querystring.less
Changes how location queries are displayed in the querystring pattern.
@vangheem Please review this to death, when you get the chance.
=> Path criteria

CHANGES.rst, mockup/patterns/relateditems/pattern.js
=> Implement support for Navigation Root in relatedItems pattern by allowing an options rootPath parameter.

CHANGES.rst, mockup/js/ui/views/popover.js
https://github.com/plone/Products.CMFPlone/issues/1194
=> Fix `aria-hidden` attribute control problem on folder content panel

mockup/patterns/structure/js/views/actionmenu.js, mockup/patterns/structure/js/views/addmenu.js, mockup/patterns/structure/js/views/app.js, mockup/patterns/structure/js/views/columns.js, mockup/patterns/structure/js/views/generic-popover.js, mockup/patterns/structure/js/views/rearrange.js, mockup/patterns/structure/js/views/selectionbutton.js, mockup/patterns/structure/js/views/selectionwell.js, mockup/patterns/structure/js/views/table.js, mockup/patterns/structure/js/views/textfilter.js, mockup/patterns/structure/js/views/upload.js, mockup/patterns/structure/pattern.js, mockup/patterns/structure/templates/actionmenu.xml, mockup/patterns/structure/templates/selection_button.xml, mockup/patterns/structure/templates/table.xml, mockup/patterns/structure/templates/tablerow.xml
=> cleanup requirejs depenencies for structure pattern

CHANGES.rst, mockup/patterns/modal/pattern.js
enable possible grid systems in modal markup (eg. http://getbootstrap.com/javascript/#modals-grid-system)
=> fix grid system markup in plone-modal

CHANGES.rst, mockup/js/utils.js, mockup/patterns/select2/pattern.js
Same as https://github.com/plone/mockup/pull/684 but then for branch 2.1.x.
I simply cherry-picked commit 93ca15ed788ea0c7840b6bd317323f945a0d40ed from master.
Note: I don't know how to test this.
=> Escape html on 2.1.x

CHANGES.rst, mockup/patterns/markspeciallinks/pattern.js
=> Revert "provide selector option to markspeciallinks pattern(master)"

CHANGES.rst, mockup/js/utils.js, mockup/patterns/select2/pattern.js, mockup/tests/pattern-select2-test.js, mockup/tests/utils-test.js
introduce new utility method `removeHTML` and implement it to the
select2 pattern. add tests for html manipulation and select2 values.
=> fix for #706

CHANGES.rst, mockup/patterns/modal/pattern.js
https://github.com/plone/Products.CMFPlone/issues/1483
=> Plip 1483 retina image scales

CHANGES.rst, mockup/patterns/pickadate/pattern.js, mockup/patterns/pickadate/pattern.pickadate.less, mockup/tests/pattern-pickadate-test.js
see plone/Products.CMFPlone#1953
=> fix datepicker markup

.travis.yml, mockup/patterns/filemanager/pattern.js, mockup/tests/pattern-filemanager-test.js, mockup/tests/pattern-thememapper-test.js
/cc @b4oshany (but after merge to context-menu, please rebase and remove "Enable Travis"-commit)
=> Fix tests for context-menu branch

CHANGES.rst, mockup/patterns/structure/js/views/app.js, mockup/patterns/structure/js/views/textfilter.js, mockup/patterns/structure/less/pattern.structure.less
Structure pattern:
- Make action menu bar sticky.
- Make action menu more compact, so that it doesn't break into a newline early.
- Use more tooltips in the action menu.
Merge all these:
https://github.com/plone/plone.app.content/pull/138
https://github.com/plone/mockup/pull/811
https://github.com/plone/Products.CMFPlone/pull/2164
=> Structure pattern UI optimizations

CHANGES.rst, mockup/patterns/relateditems/pattern.js
Merge together:
https://github.com/plone/mockup/pull/823
https://github.com/plone/Products.CMFPlone/pull/2218
=> Related items pattern: Avoid double initialization of Select2.

CHANGES.rst, mockup/patterns/moment/pattern.js
Obsoletes: https://github.com/plone/mockup/pull/662
=> Fixing problems with wrong relative date translations for norwegian sites

mockup/patterns/relateditems/pattern.js
=> When an item is already selected, update the breadcrumbs accordingly

mockup/patterns/tinymce/less/pattern.tinymce.less
=> Use full path for tinymce fonts. 

CHANGES.rst, mockup/index.html, mockup/tests/files/mapper.html
refs. https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/compatibility/cc288325(v=vs.85)
=> Get rid of obsolete X-UA-Compatible header

CHANGES.rst, package-lock.json
See https://github.com/npm/npm/blob/v5.0.0/doc/files/package-lock.json.md
"package-lock.json is automatically generated for any operations where npm modifies either the node_modules tree, or package.json. It describes the exact tree that was generated, such that subsequent installs are able to generate identical trees, regardless of intermediate dependency updates.
This file is intended to be committed into source repositories"
=> package-lock.json is supposed to be under revision control

CHANGES.rst, mockup/patterns/structure/less/pattern.structure.less
Seen in folder contents, available column selection.
=> Fix spacing for attribute-columns popover.

mockup/patterns/relateditems/pattern.js, mockup/patterns/relateditems/pattern.relateditems.less, mockup/patterns/select2/pattern.select2.less, news/902.fix
Fixes plone/Products.CMFPlone#2785
=> Fix misalignment in regular Select 2 widgets

mockup/patterns/autotoc/pattern.js, mockup/patterns/tinymce/js/links.js, mockup/tests/pattern-autotoc-test.js, mockup/tests/pattern-tinymce-test.js, news/922.bugfix
=> Fix Tinymce pattern: Link popup looses tab selection on active linktype

mockup/patterns/sortable/pattern.js, news/919.bugfix
Fixes [https://github.com/plone/Products.CMFPlone/issues/2851](https://github.com/plone/Products.CMFPlone/issues/2851) 
Added a minimum distance to trigger dragging.
=> Fixed drag problem on click on sortable items in folder contents.

mockup/js/config.js, mockup/tests/pattern-structure-test.js, news/914.feature, package.json, yarn.lock
WIP. Currently failing with:
```
Structure traverse links
✗ test navigate to folder push states
undefined is not an object (evaluating 'history.pushed.url')
tests/pattern-structure-test.js:1306:28
✗ test navigate to folder push states - urlStructure
undefined is not an object (evaluating 'history.pushed.url') A
tests/pattern-structure-test.js:2153:28
✗ test navigate to folder push states - pushStateUrl
undefined is not an object (evaluating 'history.pushed.url')
tests/pattern-structure-test.js:2190:28
```
See: https://github.com/plone/mockup/pull/913#issuecomment-505065684
=> Upgrade sinon

mockup/patterns/structure/templates/paging.xml, news/948.feature
=> Do not use lists where items are not lists

mockup/patterns/inlinevalidation/pattern.js, news/971.bugfix
=> pat-inlinevalidation: Fix bug where drop downs would not get validated

mockup/patterns/structure/js/views/textfilter.js, news/952.bugfix
=> Add a hidden label to the search input

mockup/js/ui/views/popover.js, news/968.bugfix
=> close popovers when ESC is pressed

mockup/patterns/tinymce/templates/link.xml, news/946.enhancement
=> Tinymce pattern: add tests for the tabs in template link.xml

mockup/patterns/querystring/pattern.js, news/982.bugfix
=> Set RelativeDateWidget value on edit

mockup/patterns/moment/pattern.js, news/987.bugfix
See https://github.com/plone/Products.CMFPlone/issues/2953 for details
=> Fix regression with moment relative date not localized

mockup/patterns/structure/js/views/selectionwell.js, news/997.bugfix
This fixes https://github.com/plone/mockup/issues/997
=> Fix internationalization of "Filter" placeholder in selected items dialog

mockup/patterns/tinymce/js/links.js, news/1010.bugfix
Fixed wrong translation text option in links popup
=> fixed external description translation

Makefile, mockup/js/config.js, news/980.bugfix, package.json, yarn.lock
Fix broken ``make docs`` task.
Now do:
``make bootstrap`` to install missing dependencies and a necessary symlink within node_modules
``make docs``
then do:
``python2 -m SimpleHTTPModule`` and open http://localhost:8000/mockup/ in the browser.
=> Fix building of the docs bundle 

.travis.yml, news/1023.feature
Do not set up tests for different browsers - we were always only testing in phantomjs.
Set up Travis caches.
=> Simpliy Travis configuration.

mockup/patterns/querystring/pattern.js, news/1043.bugfix
=> Fix for sort_reversed checkbox in pat-querystring

news/1071.bugfix, src/pat/passwordstrength/passwordstrength.js, src/pat/passwordstrength/passwordstrength.test.js
We were not done (and i thought the PR was still a draft). 
Fixed the tests.
=> Es6 passwordstrength

news/1094.bugfix, src/pat/manageportlets/README.md, src/pat/manageportlets/manageportlets.js, src/patterns.js
=> Es6 pat-manage-portlets

README.md, news/1104.feature, src/pat/controlpanels/contentrule-elements--implementation.js, src/pat/controlpanels/contentrule-elements.js, src/pat/controlpanels/contentrules--implementation.js, src/pat/controlpanels/contentrules.js
needs https://github.com/plone/plone.app.contentrules/pull/70
=> add contentrule pattern to controlpanels

src/pat/toggle/toggle.js, src/pat/toggle/toggle.test.js
The last test: "should throw an error when it cannot find the target"
throws an error. log.error.calledOnce is false.
=> WIP toggle: fix tests

src/pat/toolbar/pattern.toolbar.scss, src/pat/toolbar/toolbar.js, src/pat/toolbar/variables.scss
see https://github.com/plone/Products.CMFPlone/issues/3414
=> implement expanded/collapsed mode

src/core/utils.js
Fix the ``resolveIcon`` cache in a way that multiple asynchronous calls for the same icon does not lead to multiple network connections to the same resource.
Instead the icon cache is prefilled with the Promise which will resolve the icon and then we await the fullfilment of the Promise.
=> fix(core utils resolveIcon): Fix resolveIcon cache.

mockup/patterns/structure/js/views/app.js
this fixes https://github.com/plone/Products.CMFPlone/issues/3464 for Plone 5.2
=> [3.x] pat-structure: fix duplicated initialization of result collection in

src/pat/structure/js/views/app.js
I broke the implememtation of `this.tableView` and fixed it again 🙈
=> fix selecting columns for pat-structure datatable

src/pat/toolbar/toolbar.js, src/pat/toolbar/toolbar.scss
Add styling again and make use CSS variables
=> Toolbar improvements

src/pat/tinymce/js/links.js, src/pat/tinymce/templates/image.xml, src/pat/tinymce/tinymce--implementation.js, src/pat/tinymce/tinymce.js
needs this 
- https://github.com/plone/Products.CMFPlone/pull/3477
- https://github.com/plone/plone.base/pull/5
also see the discussion here https://github.com/plone/plone.namedfile/issues/111
needs an upgrade step in plone.app.upgrades to load the config
=> Mrtango tinymce image srcset config WIP

src/pat/structure/js/views/tablerow.js
=> Fix `pat-structure -> exclude_from_nav` for items without information

README.md, package.json, src/i18n.js, src/pat/formunloadalert/formunloadalert.js, src/pat/preventdoublesubmit/preventdoublesubmit.js, src/pat/structure/js/views/rearrange.js, src/pat/structure/js/views/table.js, src/pat/structure/js/views/textfilter.js, src/pat/tinymce/tinymce.js, widgets.pot
Fixes #1189 
I am not at all a JS guy, I just copied the script that used to work in Mockup 4 and it seems to update the widgets.pot file.
Can someone review this please?
@thet @petschki @mauritsvanrees
=> add i18n extraction script and document the use

src/patterns.js
This allows for optional form fields or other HTML‌ structure which depen on the value of form inputs.
=> feat(pat depends): Add pat-depends from @patternslib/patternslib to the build.

src/pat/relateditems/relateditems.js
=> Make `pat-relateditems`templates customizeable again via patternoptions

.github/workflows/test.yml, src/core/i18n.test.js
=> [testfix] core/i18n

src/pat/modal/modal.test.js
Fixed all ~~but test 5 and 6 ... sorry could not figure out how to successfully mock `$.ajax` with the current `$.ajax().done().fail().always()` implementation... skipped them for now.~~
UPDATE: somehow this works now ... but it doesn't look very nice in my opinion.
/cc @thet @frapell
=> [testfix] pat-modal

src/core/i18n-wrapper.js, src/pat/structure/js/views/table.js, src/pat/structure/js/views/tablerow.js, src/pat/structure/templates/tablerow.xml
=> Enhanced i18n to enable `pat-structure` review_state translation.

package.json, src/pat/tinymce/tinymce--implementation.js, src/pat/tinymce/tinymce.js, yarn.lock
This PR fixes gh-1253 and also I have refactored the `initLanguage` method to not use a callback, but instead properly await it.
In addition, I added a check so only valid plugins (plugins that can be imported) are included.
=> `pat tinymce` Improve tinymce async initialization

Makefile
=> maint: define YARN in our Makefile.

src/pat/recurrence/recurrence.js
=> Initial editing and correct time for additional RDATE values

jest.config.js, package.json, src/pat/datatables/datatables.js, src/pat/structure/structure.test.js, src/setup-tests.js, yarn.lock
See commit messages.
Makes https://github.com/plone/mockup/pull/1290 obsolete.
Thanks @rnixx and @toalba !
=> Datatables fixes

src/patterns.js
With this we can re-enable `toggle-all` functionality in controlpanel templates (for example group membership panel) see https://github.com/plone/Products.CMFPlone/issues/3740
=> Add `pat-checklist`

.github/workflows/test.yml, src/pat/recurrence/recurrence.js, src/pat/recurrence/recurrence.scss, src/pat/recurrence/recurrence.test.js, src/pat/recurrence/templates/display.xml, src/pat/recurrence/templates/form.xml
- Fix various issues when changing/re-editing data.
- fixed monthly/yearly option selectors change events
=> Recurrence widget UI issues

package.json, yarn.lock
Change-log: https://blog.getbootstrap.com/2023/03/24/bootstrap-5-3-0-alpha2/
=> update bootstrap to 5.3.0-alpha2

src/pat/recurrence/recurrence.js
=> fix(pat recurrence): Fixes for 'Repeat on' for Yearly and Monthly options

src/pat/tinymce/js/links.js
fixes #1302
for Plone 6.1 there is another PR #1304
=> Fix external images having picturevariants

package.json, yarn.lock
=> Update Bootstrap Icons

src/pat/recurrence/recurrence.js
=> Fix `pat-recurrence` default selected "range option" [master]

src/pat/tinymce/js/links.js
fixes https://github.com/plone/Products.CMFPlone/issues/3768
=> Do not remove current paragraph when inserting image in TinyMCE. [5.0.x]

src/pat/tinymce/js/links.js
fixes https://github.com/plone/Products.CMFPlone/issues/3768
=> Do not remove current paragraph when inserting image in TinyMCE [master]

package.json, webpack.config.js
- fix: Include the select2 patch in the npm package.
- fix: Get the remote bundle name from package.json.
=> Small improvements.

src/pat/tinymce/tinymce--implementation.js
=> Fix TinyMCE external url handling [master]

src/pat/structure/js/views/app.js
=> `pat-structure` filter popover fix [5.1.x]

src/pat/structure/js/views/app.js
=> `pat-structure` filter popover fix [master]

package.json, yarn.lock
=> 5.1.x maintenance

src/pat/tinymce/js/links.js
fixes https://github.com/plone/Products.CMFPlone/issues/3910
=> Fix duplicated image node when updateing already inserted image. [master]

src/pat/modal/modal.js
Fixes #1381 
@petschki can you check if this syntax is correct?
=> Translate Close text as aria-label

package.json, src/pat/modal/modal.js, yarn.lock
=> Fix duplicated `portalMessage` in modal

package.json, src/pat/structure/structure.scss, yarn.lock
Since TinyMCE 7.3.0 there are `css-loader` Errors. See https://github.com/tinymce/tinymce/issues/9829 ... I've pinned to `7.2.1` for now until this is solved.
=> Package housekeeping

package.json, src/pat/modal/modal.js, src/pat/structure/structure.scss, yarn.lock
and some minor sass warnings in `structure.scss`
=> Fix doubled modal message [5.1.x]

src/pat/tinymce/tinymce--implementation.js, src/pat/tinymce/tinymce.test.js
=> `pat-tinymce` save value on 'change' event to fix validation

package.json, yarn.lock
=> Fix bug with npm-run-all and npx

src/pat/contentbrowser/src/App.svelte, src/pat/contentbrowser/src/utils.js
=> fix wrong vocabularyUrl lookup when `@@getSource` view is used

src/pat/tinymce/js/links.js
fixes https://github.com/plone/Products.CMFPlone/issues/4083
=> fix(pat tinymce): Fix Link/Image modal when inline mode is activated.

src/pat/contentbrowser/src/ContentBrowser.svelte
fixes #1410 and #1418 
https://github.com/user-attachments/assets/d8da56f0-a359-4124-9ea1-8ce95336c70a
=> `pat-contentbrowser` improvements

jest.config.js, package.json, src/pat/datatables/datatables.test.js, src/pat/structure/js/views/columns.js, src/pat/structure/structure.scss, src/pat/structure/structure.test.js, yarn.lock
~~Updated `Patternslib=9.10.1-beta.2`~~
Talked with @thet and we agreed to not use patternslib beta in 5.2 final.
=> Prepare 5.2 final

src/pat/contentbrowser/contentbrowser.js, src/pat/contentbrowser/src/App.svelte, src/pat/contentbrowser/src/ContentBrowser.svelte, src/pat/contentbrowser/src/ContentStore.js, src/pat/contentbrowser/src/utils.js
=> `pat-contentbrowser` fixes and feature

src/pat/tinymce/tinymce--implementation.js, src/pat/tinymce/tinymce.js, src/pat/tinymce/tinymce.test.js
update init options for the tinymce editor, set the language code after underscore replacement
=> fix(pat tinymce): set language code for init options

src/pat/tinymce/tinymce--implementation.js
As discussed here https://github.com/plone/plone.staticresources/issues/379 we're quickfixing the menubar value type until its fixed in `plone.base`
=> Fix "menubar" setting

src/pat/autotoc/README.md, src/pat/autotoc/autotoc.js, src/pat/autotoc/autotoc.test.js
…d section if applicable.
https://github.com/Patternslib/Patterns/pull/1245
https://github.com/plone/mockup/pull/1460
https://github.com/plone/plonetheme.barceloneta/pull/399
Plone 6 version of: https://github.com/plone/mockup/pull/1455
this sets a class for form-tabs with required fields and a class for invalid form-tabs.
=> Autotoc validation (Plone 6.0)

src/pat/autotoc/autotoc.js, src/pat/autotoc/autotoc.test.js
Plone 6.0 version of: https://github.com/plone/mockup/pull/1462
=>  Show required indicator for tabs with reuqired multicheckbox fields (Plone 6.0)

src/pat/autotoc/autotoc.js, src/pat/autotoc/autotoc.scss, src/pat/autotoc/autotoc.test.js
=> Revert "Make Autotoc tab markup compatible with Bootstrap"
